// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChangePasswordCard: typeof import('./src/components/Form/ChangePasswordCard.vue')['default']
    FormProfileCard: typeof import('./src/components/Form/FormProfileCard.vue')['default']
    ProfilePictureCard: typeof import('./src/components/Form/ProfilePictureCard.vue')['default']
    ProfilePictureUpdater: typeof import('./src/components/ProfilePictureUpdater.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/components')['VApp']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/components')['VAppBarNavIcon']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VDivider: typeof import('vuetify/components')['VDivider']
    VForm: typeof import('vuetify/components')['VForm']
    VLayout: typeof import('vuetify/components')['VLayout']
    VList: typeof import('vuetify/components')['VList']
    VListGroup: typeof import('vuetify/components')['VListGroup']
    VListItem: typeof import('vuetify/components')['VListItem']
    VMain: typeof import('vuetify/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VTextField: typeof import('vuetify/components')['VTextField']
    VThemeProvider: typeof import('vuetify/components')['VThemeProvider']
  }
}
