// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChangePasswordCard: typeof import('./src/components/Form/ChangePasswordCard.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    ForcePasswordForm: typeof import('./src/components/Form/ForcePasswordForm.vue')['default']
    FormProfileCard: typeof import('./src/components/Form/FormProfileCard.vue')['default']
    NewUserForm: typeof import('./src/components/Form/NewUserForm.vue')['default']
    ProfilePictureCard: typeof import('./src/components/Form/ProfilePictureCard.vue')['default']
    ProfilePictureUpdater: typeof import('./src/components/ProfilePictureUpdater.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./src/components/Form/UserForm.vue')['default']
    UserPictureForm: typeof import('./src/components/Form/UserPictureForm.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/components')['VAppBarNavIcon']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VForm: typeof import('vuetify/components')['VForm']
    VLayout: typeof import('vuetify/components')['VLayout']
    VList: typeof import('vuetify/components')['VList']
    VListGroup: typeof import('vuetify/components')['VListGroup']
    VListItem: typeof import('vuetify/components')['VListItem']
    VMain: typeof import('vuetify/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VOverlay: typeof import('vuetify/components')['VOverlay']
    VPagination: typeof import('vuetify/components')['VPagination']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VSelect: typeof import('vuetify/components')['VSelect']
    VTable: typeof import('vuetify/components')['VTable']
    VTextField: typeof import('vuetify/components')['VTextField']
    VThemeProvider: typeof import('vuetify/components')['VThemeProvider']
    VToolbar: typeof import('vuetify/components')['VToolbar']
    VToolbarTitle: typeof import('vuetify/components')['VToolbarTitle']
  }
}
